# Generated by Django 3.1.4 on 2020-12-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('phoneNo', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
